services:
  n8n:
    build: .
    image: n8n-with-workflows
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      # Basic settings
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      NODE_ENV: ${NODE_ENV:-production}
      
      # Database settings (SQLite - default)
      DB_TYPE: sqlite
      DB_SQLITE_VACUUM_ON_STARTUP: ${DB_SQLITE_VACUUM_ON_STARTUP:-false}
            
      # Webhook settings
      WEBHOOK_URL: ${WEBHOOK_URL:-http://localhost:5678/}
      N8N_PAYLOAD_SIZE_MAX: ${N8N_PAYLOAD_SIZE_MAX:-16}
      
      # Execution settings
      EXECUTIONS_PROCESS: ${EXECUTIONS_PROCESS:-main}
      EXECUTIONS_TIMEOUT: ${EXECUTIONS_TIMEOUT:-3600}
      EXECUTIONS_TIMEOUT_MAX: ${EXECUTIONS_TIMEOUT_MAX:-7200}
      EXECUTIONS_DATA_SAVE_ON_ERROR: ${EXECUTIONS_DATA_SAVE_ON_ERROR:-all}
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: ${EXECUTIONS_DATA_SAVE_ON_SUCCESS:-all}
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: ${EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS:-true}
      
      # External services API Keys (for LLMs)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      
      # Timezone
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-Asia/Tokyo}
      TZ: ${TZ:-Asia/Tokyo}